export const SAVE_EMPLOYEES_LIST = "SAVE_EMPLOYEES_LIST";
export const SAVE_EMPLOYEE_DETAIL = "SAVE_EMPLOYEE_DETAIL";
export const CLEAR_EMPLOYEE_DETAIL = "CLEAR_EMPLOYEE_DETAIL";
export const SAVE_PREVIOUSLY_ADDED_EMPLOYEE = "SAVE_PREVIOUSLY_ADDED_EMPLOYEE";
export const CLEAR_PREVIOUSLY_ADDED_EMPLOYEE =
  "CLEAR_PREVIOUSLY_ADDED_EMPLOYEE";
export const SAVE_EMPLOYEES_BY_PAGE = "SAVE_EMPLOYEES_BY_PAGE";
export const CLEAN_EMPLOYEES = "CLEAN_EMPLOYEES";
